project_id = "vozaayivzggkpazehdxr"

[functions.send-email]
verify_jwt = false

[functions.track-guest-order]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-abandoned-cart-emails]
verify_jwt = false
